### ISSUE TITLE
Unable to get the chart element in function binded to callbackClick

### ISSUE THREAD

**Issue by nvuillam** [SalesforceLabs/LightningWebChartJS#131]
First, thanks for this great LWC that renders very well !

But we have an issue when we try to click on it

We display the foillowing simple graph with bars

![image](https://user-images.githubusercontent.com/17500430/234985683-0959f793-c324-44a5-9760-54fe66daed9d.png)

When we click on it, we need to retrieve the data that has been used to build the column (that contains an id that we need to call another API )

We binded a method in the LWC to catch the click event

```html
              <c-chart lwc:ref="c-chart" type="bar" events='["click"]' callback-click={handleChartClick}
                    stylecss="position: relative; margin: auto;">
                    <c-dataset labels={columnsAsString}>
                        <c-data detail={graphDataAsString} backgroundcolor='[
                        "rgba(82, 183, 216, 1)",
                        "rgba(225, 96, 50, 1)",
                        "rgba(255, 176, 59, 1)",
                        "rgba(84, 167, 123, 1)",
                        "rgba(79, 210, 210, 1)",
                        "rgba(226, 135, 178 ,1)"
                        ]' bordercolor='[
                        "rgba(82, 183, 216, 1)",
                        "rgba(225, 96, 50, 1)",
                        "rgba(255, 176, 59, 1)",
                        "rgba(84, 167, 123, 1)",
                        "rgba(79, 210, 210, 1)",
                        "rgba(226, 135, 178, 1)"
                        ]' borderwidth="1">
                        </c-data>
                    </c-dataset>
                    <c-title text="Niveaux de couverture"></c-title>
                    <c-animation duration="1000" easing="easeInSine"> </c-animation>
                    <c-cartesian-category-axis axis="x" position="top"></c-cartesian-category-axis>
                    <c-tooltip enabled="false"></c-tooltip>
                </c-chart>
```
Undepending what we tried, we have a crash... do you have a way to retrieve the click element info in a LWC method ?

Below the different stuff we tried, with crash comments

```javascript
    handleChartClick(evt,element) {   
        console.log('handleChartClick');
        debugger;
        // Try calling c-chart getElementAtEventChart(event) function
        // const chartLwcInstance = this.template.querySelector("c-chart"); // Triggers error because the this is the chart this, not the LWC this
        // const chartClickElement = chartLwcInstance.getElementAtEventChart(element);

        // Or try calling directly the chart to get the element
        const chartClickElement = this.chart.getElementAtEvent(element); 
        /* this.chart is set, but Triggers the following error
        "TypeError: Cannot read properties of undefined (reading 'getBoundingClientRect')
            at ut.getRelativePosition (eval at <anonymous> (eval at createRedConnector$LWS (https://static.lightning.force.com/cs162/auraFW/javascript/2kszAdlijI-L2tQGa5JU9w/aura_proddebug.js:37628:12)), <anonymous>:7:206197)
            at de (eval at <anonymous> (eval at createRedConnector$LWS (https://static.lightning.force.com/cs162/auraFW/javascript/2kszAdlijI-L2tQGa5JU9w/aura_proddebug.js:37628:12)), <anonymous>:7:68561)
            at Object.single (eval at <anonymous> (eval at createRedConnector$LWS (https://static.lightning.force.com/cs162/auraFW/javascript/2kszAdlijI-L2tQGa5JU9w/aura_proddebug.js:37628:12)), <anonymous>:7:69534)
            at ni.getElementAtEvent (eval at <anonymous> (eval at createRedConnector$LWS (https://static.lightning.force.com/cs162/auraFW/javascript/2kszAdlijI-L2tQGa5JU9w/aura_proddebug.js:37628:12)), <anonymous>:7:98257)
            at ni.handleChartClick (eval at <anonymous> (eval at createRedConnector$LWS (https://static.lightning.force.com/cs162/auraFW/javascript/2kszAdlijI-L2tQGa5JU9w/aura_proddebug.js:37628:12)), <anonymous>:131:44)
            at ni.handleEvent (eval at <anonymous> (eval at createRedConnector$LWS (https://static.lightning.force.com/cs162/auraFW/javascript/2kszAdlijI-L2tQGa5JU9w/aura_proddebug.js:37628:12)), <anonymous>:7:101064)
            at ni.eventHandler (eval at <anonymous> (eval at createRedConnector$LWS (https://static.lightning.force.com/cs162/auraFW/javascript/2kszAdlijI-L2tQGa5JU9w/aura_proddebug.js:37628:12)), <anonymous>:7:100479)
            at i (eval at <anonymous> (eval at createRedConnector$LWS (https://static.lightning.force.com/cs162/auraFW/javascript/2kszAdlijI-L2tQGa5JU9w/aura_proddebug.js:37628:12)), <anonymous>:7:99844)
            at Ae.<computed> (eval at <anonymous> (eval at createRedConnector$LWS (https://static.lightning.force.com/cs162/auraFW/javascript/2kszAdlijI-L2tQGa5JU9w/aura_proddebug.js:37628:12)), <anonymous>:7:77607)
            at eval (eval at createRedConnector$LWS (https://static.lightning.force.com/cs162/auraFW/javascript/2kszAdlijI-L2tQGa5JU9w/aura_proddebug.js:37628:12), <anonymous>:3271:25)"
        */
    }
```

Many thanks for your help ❤️ 

cc @victorgz @scolladon

**Comment by victorgz** [comment]
Hi @nvuillam , thanks for your feedback !
We've had a look and good news is that we've got the answer for you 😄  Two things to point out:

1. In your callback function, you need to use the `event` variable instead of `element` when calling the `getElementAtEventChart()` function. 

2. We're aware of this situation and the solution is to use arrow function (we've a section which explains that in our doc - "[How can I use the callbacks in LWC and access properties of the current component](https://salesforcelabs.github.io/LightningWebChartJS/docs/general/faq.html#:~:text=How%20can%20I%20use%20the%20callbacks%20in%20LWC%20and%20access%20properties%20of%20the%20current%20component%3F)?")
When you use a class-method for your callback, `this` will point to the context of that callback (so in our case, the library).
The solution is to use an arrow-function, so you can keep the context of `this` in your LWC

```
handleChartClick = (evt) => {
	const chartLwcInstance = this.template.querySelector("c-chart");
        const chartClickElement = chartLwcInstance.getElementAtEventChart(evt);
}
```

That being said, you could do that in your code but it is not recommended as the `chart` variable belongs to the library and you don't have a direct visibility onto it.
```
handleChartClick(evt){
	const result = this.chart.getElementAtEvent(evt);
}
```

Hope it helps and don't hesitate to come back to us if it doesn't fix the issue for you.
Otherwise, feel free to close the issue 👍

**Comment by nvuillam** [comment]
@victorgz we'll try that and close the issue when confirmed it works, many thanks for your quick answer :)

**Comment by nvuillam** [comment]
Solved, thanks :)
